/**
 * Clock in / clock out, with the geofence decided here rather than in the
 * browser.
 *
 * Attendance drives pay and is the record of who was with a patient and when.
 * A check performed in the phone is not a control: the page can be edited, the
 * position spoofed from developer tools in a few seconds, and the underlying
 * store function called directly from the console with any coordinates at all.
 * So the browser's only job is to obtain the best fix it can and report it.
 * Everything that matters — which patient this shift is for, where that
 * patient actually is, how far away that is, and whether that is acceptable —
 * is resolved on this side from the HCA's signed session cookie.
 *
 * The shift is also the source of truth for the patient. The dashboard used to
 * assume patients[0] of whichever client had assigned_hca_id set, which is
 * wrong the moment an HCA serves two patients — it geofenced them against the
 * wrong address and filed the Cardex under the wrong person.
 */
import { getSupabaseAdmin, serviceRoleConfigured, configError } from '../../../lib/supabaseAdmin';
import { getSession, sessionSecretConfigured } from '../../../lib/serverAuth';
import { settingsFromDb } from '../../../lib/platformSettings';
import {
  resolveCareLocation, evaluateFix, describeVerdict, policyFromSettings, num,
} from '../../../lib/geofence';
import { todayIso } from '../../../lib/scheduling';

function clientIp(req) {
  return (req.headers['x-forwarded-for'] || '').split(',')[0].trim() || req.socket?.remoteAddress || null;
}

/** Record every decision, allowed or refused. A refusal that leaves no trace
 *  is indistinguishable from an HCA who simply never turned up. */
async function recordException(db, row) {
  try { await db.from('attendance_exceptions').insert(row); }
  catch { /* never let the audit write block a legitimate clock-in */ }
}

export default async function handler(req, res) {
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' });
  if (!serviceRoleConfigured() || !sessionSecretConfigured()) return configError(res);

  const session = getSession(req);
  if (!session || session.role !== 'hca') return res.status(401).json({ error: 'Not signed in.' });

  const db = getSupabaseAdmin();
  const b = req.body || {};
  const action = b.action === 'out' ? 'out' : 'in';
  const verb   = action === 'in' ? 'clock in' : 'clock out';

  // ── The shift. Never taken from the request. ──────────────────────────────
  const today = todayIso();
  let shift = null;

  if (action === 'out') {
    const { data } = await db.from('shifts').select('*')
      .eq('hca_id', session.id).eq('status', 'in-progress')
      .order('clock_in', { ascending: false }).limit(1).maybeSingle();
    shift = data;
    if (!shift) return res.status(409).json({ error: 'You are not currently clocked in.' });
  } else {
    // Today's scheduled shift, generated by the placement.
    const { data } = await db.from('shifts').select('*')
      .eq('hca_id', session.id).eq('date', today)
      .in('status', ['scheduled', 'in-progress'])
      .order('start_time', { ascending: true }).limit(1).maybeSingle();
    shift = data;
    if (shift?.status === 'in-progress') {
      return res.status(409).json({ error: 'You are already clocked in for this shift.' });
    }
  }

  // ── Where this shift is supposed to be. ───────────────────────────────────
  const clientId  = shift?.client_id  || null;
  const patientId = shift?.patient_id || null;

  let client = null;
  if (clientId) {
    const { data } = await db.from('clients')
      .select('id, name, location, address, lat, lng, patients, assigned_hca_id')
      .eq('id', clientId).maybeSingle();
    client = data;
  }
  if (!client) {
    // No scheduled shift and no placement — there is nowhere to be.
    const { data } = await db.from('clients')
      .select('id, name, location, address, lat, lng, patients, assigned_hca_id')
      .eq('assigned_hca_id', session.id).limit(1).maybeSingle();
    client = data;
  }
  if (!client && action === 'in') {
    return res.status(409).json({ error: 'You have no active placement. Contact your E-Vive coordinator.' });
  }

  const patients = client?.patients || [];
  const patient  = (patientId && patients.find(p => p.id === patientId)) || patients[0] || null;
  const target   = resolveCareLocation(client, patient);

  // ── Policy, then the decision. ────────────────────────────────────────────
  const { data: settingsRow } = await db.from('platform_settings').select('*').eq('id', 1).maybeSingle();
  const policy = policyFromSettings(settingsFromDb(settingsRow));

  const result = evaluateFix({
    lat: b.lat, lng: b.lng, accuracyM: b.accuracyM, target, policy,
  });
  const message = describeVerdict(result, verb);

  const auditBase = {
    hca_id: session.id,
    shift_id: shift?.id || null,
    client_id: client?.id || null,
    patient_id: patient?.id || null,
    action,
    lat: result.lat, lng: result.lng,
    accuracy_m: result.accuracyM,
    distance_m: result.distanceM,
    allowed_m: result.allowedM,
    verdict: result.verdict,
    reference_source: result.referenceSource,
    sample_count: Number.isFinite(num(b.sampleCount)) ? Math.round(num(b.sampleCount)) : null,
    enforcement: policy.enforcement,
    ip: clientIp(req),
    user_agent: req.headers['user-agent'] || null,
  };

  if (!result.ok) {
    await recordException(db, { ...auditBase, allowed: false, detail: message });
    return res.status(422).json({ error: message, verdict: result.verdict, geofence: publicResult(result) });
  }

  // Anything other than a clean fix inside the fence is worth Admin's
  // attention, even though it is permitted.
  if (result.verdict !== 'inside') {
    await recordException(db, { ...auditBase, allowed: true, detail: message });
  }

  // ── Apply. ────────────────────────────────────────────────────────────────
  const now = new Date().toISOString();

  if (action === 'in') {
    const patch = {
      status: 'in-progress', clock_in: now,
      clock_in_lat: result.lat, clock_in_lng: result.lng,
      clock_in_accuracy_m: result.accuracyM,
      clock_in_distance_m: result.distanceM,
      clock_in_verdict: result.verdict,
    };
    let row;
    if (shift) {
      ({ data: row } = await db.from('shifts').update(patch).eq('id', shift.id).select().single());
    } else {
      // Unscheduled attendance (an emergency cover shift). Allowed, but it is
      // created here rather than by the browser so it inherits the same checks.
      ({ data: row } = await db.from('shifts').insert({
        hca_id: session.id, client_id: client?.id || null, patient_id: patient?.id || null,
        date: today, type: 'day', start_time: '07:00', notes: 'Unscheduled — created at clock-in',
        ...patch,
      }).select().single());
    }
    await db.from('activity_log').insert({
      type: 'hca_clock_in',
      data: {
        hcaId: session.id, shiftId: row?.id, clientId: client?.id, patientId: patient?.id,
        distanceM: result.distanceM, accuracyM: result.accuracyM, verdict: result.verdict,
      },
    });
    return res.status(200).json({ ok: true, shift: mapShift(row), message, geofence: publicResult(result),
      patient: patient ? { id: patient.id, name: patient.name } : null,
      client:  client  ? { id: client.id,  name: client.name  } : null });
  }

  const { data: row } = await db.from('shifts').update({
    status: 'completed', clock_out: now,
    clock_out_lat: result.lat, clock_out_lng: result.lng,
    clock_out_accuracy_m: result.accuracyM,
    clock_out_distance_m: result.distanceM,
    clock_out_verdict: result.verdict,
  }).eq('id', shift.id).select().single();

  await db.from('activity_log').insert({
    type: 'hca_clock_out',
    data: {
      hcaId: session.id, shiftId: shift.id, clientId: client?.id,
      distanceM: result.distanceM, accuracyM: result.accuracyM, verdict: result.verdict,
    },
  });
  return res.status(200).json({ ok: true, shift: mapShift(row), message, geofence: publicResult(result) });
}

/** What the HCA's browser is allowed to see of the decision. The reference
 *  coordinates themselves are not returned — knowing the exact centre and
 *  radius of the fence is the one thing that makes it easy to defeat. */
function publicResult(r) {
  return {
    verdict: r.verdict, ok: r.ok,
    distanceM: r.distanceM, accuracyM: r.accuracyM, radiusM: r.radiusM,
  };
}

function mapShift(r) {
  if (!r) return null;
  return {
    id: r.id, placementId: r.placement_id, hcaId: r.hca_id, clientId: r.client_id,
    patientId: r.patient_id, date: r.date, type: r.type, startTime: r.start_time,
    status: r.status, clockIn: r.clock_in, clockOut: r.clock_out,
    clockInLat: r.clock_in_lat, clockInLng: r.clock_in_lng,
    clockOutLat: r.clock_out_lat, clockOutLng: r.clock_out_lng,
    notes: r.notes, linkedEventId: r.linked_event_id,
  };
}
